// fpgatop.sv
// Tanvir Kaur & Ethan Spooner Group Project – March 2026
// Top-level integration for oscilloscope UI + ADC + trigger
// This file instantiates the lab4 module generated by Platform
// Designer and connects the FPGA pins to the module pins.

//		input  wire       clk50_clk,             //          clk50.clk
//		output wire [7:0] leds_export,           //           leds.export
//		output wire       ltc2308_0_adc0_sck,    // ltc2308_0_adc0.sck
//		input  wire       ltc2308_0_adc0_sdo,    //               .sdo
//		output wire       ltc2308_0_adc0_sdi,    //               .sdi
//		output wire       ltc2308_0_adc0_convst, //               .convst
//		input  wire       reset_n_reset_n        //        reset_n.reset_n



module fpgatop (
    input  logic clk50,
    input  logic s1,                // global reset (active high)
    input  logic s2,                // trigger mode button (active high)
    input  logic reset_button,      // reset level + timebase

    // Encoder #1 (trigger level)
    input  logic enc1a, enc1b,

    // Encoder #2 (timebase)
    input  logic enc2a, enc2b,

    // ADC pins
    input  logic ADC_SDO,
    output logic ADC_CONVST, ADC_SDI, ADC_SCK,

    output logic [7:0] LED
);

    // 1. Rotary Encoder #1 for trigger level
	 
    logic enc_level_up, enc_level_down;

    rotary_encoder level_enc (
        .clk50(clk50),
        .reset_n(s1),
        .enc_a(enc1a),
        .enc_b(enc1b),
        .up_pulse(enc_level_up),
        .down_pulse(enc_level_down)
    );


    // 2. Rotary Encoder #2 for timebase
	 
    logic enc_time_up, enc_time_down;

    rotary_encoder time_enc (
        .clk50(clk50),
        .reset_n(s1),
        .enc_a(enc2a),
        .enc_b(enc2b),
        .up_pulse(enc_time_up),
        .down_pulse(enc_time_down)
    );


    // 3. Control registers (UI state machine)
   
    logic [11:0] trig_level, timebase;
    logic [1:0]  trig_mode;
    logic enable;

    control_registers ui (
        .clk(clk50),
        .reset(!s1),                 // active-high reset inside module
        .trigger_mode(s2),                     // mode button
        .enc_level_up(enc_level_up),
        .enc_level_down(enc_level_down),
        .enc_time_up(enc_time_up),
        .enc_time_down(enc_time_down),
        .trig_level(trig_level),
        .trig_mode(trig_mode),
        .timebase(timebase),
        .enable(enable)
    );

    // 4. Trigger logic
    
    logic trigger_fire;
    logic [11:0] sample_from_adc;

    trigger trig0 (
        .clk(clk50),
        .sample_in(sample_from_adc),
        .trig_level(trig_level),
        .trig_mode(trig_mode),
        .enable(enable),
        .trigger_fire(trigger_fire)
    );

    // 5. Platform Designer system (ADC + VGA + FIFO)

    fpga fpga_0 (
        .clk50_clk(clk50),
        .reset_n_reset_n(s1),

        // ADC
        .ltc2308_0_adc0_sdo(ADC_SDO),
        .ltc2308_0_adc0_convst(ADC_CONVST),
        .ltc2308_0_adc0_sdi(ADC_SDI),
        .ltc2308_0_adc0_sck(ADC_SCK),

        // LEDs
        .leds_export(LED)
    );

endmodule

